
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  scrape_configs:
    - job_name: 'vibra-api'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['vibra-api:8080']
